apiVersion: v1
kind: Pod
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: docker.io/vulhub/php:8.1-backdoor
        ports:
        - containerPort: 80

# THE VOLUME CONFIG IS BELOW --------------------------------------
        volumeMounts:
        - mountPath: /yaml # Path of the volume in the container
          name: yaml-volume

      volumes:
      - name: yaml-volume
        hostPath:
          path: /root/yaml # Path of the directory on the Host (node)
          type: Directory # DirectoryOrCreate, FileOrCreate

